all:
	pdflatex RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.tex 
	bibtex RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.aux
	pdflatex RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.tex 
	pdflatex RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.tex 
	@mv RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.aux build/.
	@mv RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.bbl build/.
	@mv RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.blg build/.
	@mv RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.log build/.
	@mv RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.pdf build/.
	@mv RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.toc build/.

clean:
	@rm build/RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.aux
	@rm build/RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.bbl
	@rm build/RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.blg
	@rm build/RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.log
	@rm build/RyanBleileOrals2016_MonteCarloTransportAndPortablePerformanceTechniques.toc
